Backend qtagg is interactive backend. Turning interactive mode on.
  0%|          | 0/1250 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "/home/dgehrig/Documents/projects/ev/ev/scripts/train.py", line 91, in val
    ret = train(loader, model, optimizer=None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/Documents/projects/ev/ev/scripts/train.py", line 62, in train
    for i, samples in enumerate(tqdm.tqdm(loader)):
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 732, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1514, in _next_data
    return self._process_data(data, worker_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1549, in _process_data
    data.reraise()
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/_utils.py", line 735, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 171, in collate
    {
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 172, in <dictcomp>
    key: collate(
         ^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 240, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'ev.spline.SE3Spline'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 191, in collate
    return {
           ^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 192, in <dictcomp>
    key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgehrig/.mamba/envs/ev/lib/python3.11/site-packages/torch/utils/data/_utils/collate.py", line 240, in collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'ev.spline.SE3Spline'>
